apiVersion: v1
kind: Service
metadata:
  name: go-kube
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comics-graphql
  annotations:
    keel.sh/policy: "glob:dev-*"
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: comics-graphql
          image: damianesteban/comics-graphql-server:dev-0ca740e